# iOS CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/ios-migrating-from-1-2/ for more details
#
---
version: 2.1
jobs:     
  test_build:
    working_directory: ~/Waves/iOS
    macos:
      xcode: "10.2.1"      
    environment:
      BUNDLER_VERSION: 2.0.2
      FL_OUTPUT_DIR: output
    shell: /bin/bash --login -eo pipefail
    steps:
      - add_ssh_keys:
          fingerprints:
            - "aa:15:14:22:f4:fe:a3:3d:5c:52:5b:20:f4:1f:3f:52"
            # - "43:eb:59:d6:49:f1:ae:81:cb:5a:ba:b8:01:64:19:39"
      - checkout
      - run:
          name: Install Submodules
          command: git submodule sync && git submodule update --init
      - restore_cache:
          key: 1-gems-{{ checksum "Gemfile.lock" }}
          name: "Restore Gemfile"
      - restore_cache:
          key: 1-gems-{{ checksum "Podfile.lock" }}
          name: "Restore Podfile"     
      - run:
          name: Configure Bundler
          command: |
            echo 'export BUNDLER_VERSION=$(cat Gemfile.lock | tail -1 | tr -d " ")' >> $BASH_ENV
            source $BASH_ENV
            sudo gem install bundler      
      - run:
          name: Bundle install or check
          command: bundle check || bundle install --path vendor/bundle
      - save_cache:
          name: Save cache Bundle
          key: 1-gems-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      - run:
          name: Bundle check loogger
          command: |
            ls -a             
      - run:
          name: CocoaPods Repo Install
          command: bundle exec pod check || curl https://cocoapods-specs.circleci.com/fetch-cocoapods-repo-from-s3.sh | bash -s cf            
      - run:
          name: CocoaPods install or check
          command: bundle exec pod check || bundle exec pod install
      - save_cache:
          name: Save cache Pods
          key: 1-gems-{{ checksum "Podfile.lock" }}
          paths:
            - Pods
            - WavesWallet-iOS.xcworkspace      
            - /Pods
            - /WavesWallet-iOS.xcworkspace
      - run:
          name: Fastlane download env
          command: bundle exec fastlane download_bundle_enviroments --verbose 
      - run:
          name: Fastlane Build
          command: bundle exec fastlane test_build_projet --verbose
          no_output_timeout: 60m
      - run:
          name: Fastlane Upload to Testflight
          command: bundle exec fastlane test_upload_testflight --verbose
          no_output_timeout: 720m
      - store_artifacts:
          path: ~/Waves/iOS/Output
      - store_test_results:
          path: Store/Test
  prod_build:
    working_directory: ~/Waves/iOS
    macos:
      xcode: "10.2.1"     
    environment:
      BUNDLER_VERSION: 2.0.2
      FL_OUTPUT_DIR: output
      FASTLANE_LANE: waves_test
    shell: /bin/bash --login -eo pipefail
    steps:
      - add_ssh_keys:
          fingerprints:
            - "aa:15:14:22:f4:fe:a3:3d:5c:52:5b:20:f4:1f:3f:52"
            # - "43:eb:59:d6:49:f1:ae:81:cb:5a:ba:b8:01:64:19:39"
      - checkout
      - run:
          name: Install Submodules
          command: git submodule sync && git submodule update --init
      - restore_cache:
          key: gems-{{ checksum "Gemfile.lock" }}
          name: "Restore Gemfile"
      - restore_cache:
          key: pods-{{ checksum "Podfile.lock" }}
          name: "Restore Podfile"     
      - run:
          name: Configure Bundler
          command: |
            echo 'export BUNDLER_VERSION=$(cat Gemfile.lock | tail -1 | tr -d " ")' >> $BASH_ENV
            source $BASH_ENV
            sudo gem install bundler      
      - run:
          name: Bundle install or check
          command: bundle check || bundle install --path vendor/bundle
      - save_cache:
          name: Save cache Bundle
          key: gems-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      - run:
          name: Bundle check loogger
          command: |
            ls -a             
      - run:
          name: CocoaPods Repo Install
          command: bundle exec pod check || curl https://cocoapods-specs.circleci.com/fetch-cocoapods-repo-from-s3.sh | bash -s cf            
      - run:
          name: CocoaPods install or check
          command: bundle exec pod check || bundle exec pod install
      - save_cache:
          name: Save cache Pods
          key: pods-{{ checksum "Podfile.lock" }}
          paths:
            - Pods
            - WavesWallet-iOS.xcworkspace      
            - ./Pods
            - ./WavesWallet-iOS.xcworkspace
      - run:
          name: Bundle check loogger
          command: |
            ls -a 
      - run:
          name: Fastlane download env
          command: bundle exec fastlane download_bundle_enviroments --verbose 
      - run:
          name: Fastlane Build
          command: bundle exec fastlane prod_build_projet --verbose
          no_output_timeout: 60m
      - run:
          name: Fastlane Upload to Testflight
          command: bundle exec fastlane prod_upload_testflight --verbose
          no_output_timeout: 720m
      - store_artifacts:
          path: ~/Waves/iOS/Output
      - store_test_results:
          path: Store/Test            
  update_build:
    working_directory: ~/Waves/iOS
    macos:
      xcode: "10.2.1"     
    environment:
      BUNDLER_VERSION: 2.0.2
      FL_OUTPUT_DIR: output
      FASTLANE_LANE: waves_test
    shell: /bin/bash --login -eo pipefail
    steps:
      - add_ssh_keys:
          fingerprints:
            - "aa:15:14:22:f4:fe:a3:3d:5c:52:5b:20:f4:1f:3f:52"            
      - checkout
      - run:
          name: Install Submodules
          command: git submodule sync && git submodule update --init
      - restore_cache:
          key: gems-{{ checksum "Gemfile.lock" }}
          name: "Restore Gemfile"     
      - run:
          name: Configure Bundler
          command: |
            echo 'export BUNDLER_VERSION=$(cat Gemfile.lock | tail -1 | tr -d " ")' >> $BASH_ENV
            source $BASH_ENV
            sudo gem install bundler      
      - run:
          name: Bundle install or check
          command: bundle check || bundle install --path vendor/bundle
      - save_cache:
          name: Save cache Bundle
          key: gems-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      - run:
          name: Fastlane download env
          command: bundle exec fastlane download_bundle_enviroments --verbose
      - run:
          name: Fastlane increment_build_number_and_commit_push
          command: bundle exec fastlane increment_build_number_and_commit_push --verbose
          no_output_timeout: 10m
      - store_artifacts:
          path: ~/Waves/iOS/Output
      - store_test_results:
          path: Store/Test              
  dev_build:
    working_directory: ~/Waves/iOS
    macos:
      xcode: "10.2.1"    
    environment:
      BUNDLER_VERSION: 2.0.2
      FL_OUTPUT_DIR: output
    shell: /bin/bash --login -eo pipefail
    steps:
      - add_ssh_keys:
          fingerprints:
            - "aa:15:14:22:f4:fe:a3:3d:5c:52:5b:20:f4:1f:3f:52"
            - "43:eb:59:d6:49:f1:ae:81:cb:5a:ba:b8:01:64:19:39"
      - checkout
      - run:
          name: Install Submodules
          command: git submodule sync && git submodule update --init
      - restore_cache:
          key: gems-{{ checksum "Gemfile.lock" }}
          name: "Restore Gemfile"
      - restore_cache:
          key: pods-{{ checksum "Podfile.lock" }}
          name: "Restore Podfile"     
      - run:
          name: Configure Bundler
          command: |
            echo 'export BUNDLER_VERSION=$(cat Gemfile.lock | tail -1 | tr -d " ")' >> $BASH_ENV
            source $BASH_ENV
            sudo gem install bundler      
      - run:
          name: Bundle install or check
          command: bundle check || bundle install --path vendor/bundle
      - save_cache:
          name: Save cache Bundle
          key: gems-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      - run:
          name: Bundle check loogger
          command: |
            ls -a             
      - run:
          name: CocoaPods Repo Install
          command: bundle exec pod check || curl https://cocoapods-specs.circleci.com/fetch-cocoapods-repo-from-s3.sh | bash -s cf            
      - run:
          name: CocoaPods install or check
          command: bundle exec pod check || bundle exec pod install
      - save_cache:
          name: Save cache Pods
          key: pods-{{ checksum "Podfile.lock" }}
          paths:
            - Pods
            - WavesWallet-iOS.xcworkspace      
            - ./Pods
            - ./WavesWallet-iOS.xcworkspace
      - run:
          name: Bundle check loogger
          command: |
            ls -a 
      - run:
          name: Fastlane download env
          command: bundle exec fastlane download_bundle_enviroments --verbose 
      - run:
          name: Fastlane Build
          command: bundle exec fastlane dev_build_projet --verbose
          no_output_timeout: 60m      
      - store_artifacts:
          path: ~/Waves/iOS/Output
      - store_test_results:
          path: Store/Test   
  dev_log:
    working_directory: ~/Waves/iOS
    macos:
      xcode: "10.1.0"      
    environment:
      BUNDLER_VERSION: 2.0.2
      FL_OUTPUT_DIR: output
    shell: /bin/bash --login -eo pipefail
    steps:
      - add_ssh_keys:
          fingerprints:
            - "43:eb:59:d6:49:f1:ae:81:cb:5a:ba:b8:01:64:19:39"
      - checkout
      - run:
          name: Install Submodules
          command: git submodule sync && git submodule update --init
      - restore_cache:
          key: gems-{{ checksum "Gemfile.lock" }}
          name: "Restore Gemfile"
      - restore_cache:
          key: pods-{{ checksum "Podfile.lock" }}
          name: "Restore Podfile"     
      - run:
          name: Configure Bundler
          command: |
            echo 'export BUNDLER_VERSION=$(cat Gemfile.lock | tail -1 | tr -d " ")' >> $BASH_ENV
            source $BASH_ENV
            sudo gem install bundler      
      - run:
          name: Bundle install or check
          command: bundle check || bundle install --path vendor/bundle
      - save_cache:
          name: Save cache Bundle
          key: gems-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      - run:
          name: Fastlane download env
          command: bundle exec fastlane download_bundle_enviroments --verbose 
      - run:
          name: Slack
          command: bundle exec fastlane send_to_slack_artifacts --verbose
          no_output_timeout: 60m
      - store_artifacts:
          path: ~/Waves/iOS/Output
      - store_test_results:
          path: Store/Test                              
workflows:
  version: 2.1
  Release:
    jobs:
      - update_build:
          filters:
            branches:
              only: /^release/v.{2,}$/        
      - test_build:          
          filters:
            branches:
              only: /^release/v.{2,}$/
          requires:
            - update_build                
      - prod_build:          
          filters:
            branches:
              only: /^release/v.{2,}$/
          requires:
            - update_build         
  Develop:
    jobs:
      - dev_log:
          requires:
            - dev_build
      - dev_build:          
          filters:
            branches:
              only: feature/CI